<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-TPTMM17A" failures="3" tests="4" name="Testing Search" time="12.215" errors="0" timestamp="2022-09-10T16:15:30 IDT">
  <testcase classname="SearchTest" name="testDataCSV" time="7.121"/>
  <testcase classname="SearchTest" name="testDataCSV" time="1.84">
    <failure type="java.lang.AssertionError" message="expected [Cypress] but found [JavaScript End to End Testing Framework | cypress.io …]">
      <![CDATA[java.lang.AssertionError: expected [Cypress] but found [JavaScript End to End Testing Framework | cypress.io …]
at SearchTest.testDataCSV(SearchTest.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- testDataCSV -->
  <testcase classname="SearchTest" name="testDataCSV" time="1.675">
    <failure type="java.lang.AssertionError" message="expected [QTP] but found [What is QTP? | How It Works | Skill &amp;amp; Scope | Need And …]">
      <![CDATA[java.lang.AssertionError: expected [QTP] but found [What is QTP? | How It Works | Skill & Scope | Need And …]
at SearchTest.testDataCSV(SearchTest.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- testDataCSV -->
  <testcase classname="SearchTest" name="testDataCSV" time="1.501">
    <failure type="java.lang.AssertionError" message="expected [Appium] but found [Appium: Mobile App Automation Made Awesome.]">
      <![CDATA[java.lang.AssertionError: expected [Appium] but found [Appium: Mobile App Automation Made Awesome.]
at SearchTest.testDataCSV(SearchTest.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- testDataCSV -->
</testsuite> <!-- Testing Search -->
